# Site settings
title: Lucas Wiman
description: blog
github_username: lucaswiman
twitter_username: lucaswiman

# LaTeX math support via KaTeX
use_math: true

# Layout defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-seo-tag

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge

mastodon:
  - instance: hachyderm.io
    username: objectObject

exclude:
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - requirements.in
  - make-post.py
  - settings.ini
  - notebooks/
  - README.md
